name: Build and Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install

      - name: Type check
        run: bunx astro check

      - name: Build
        run: bun run build

      - name: Commit and push changes to repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Automated product feed update'

      - name: Get domain
        id: get-domain
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'src/customizations/siteproperties.json'
          prop_path: 'url'

      - name: Add CNAME to dist
        run: |
          if [[ "${{ steps.get-domain.outputs.prop }}" != *.github.io ]]; then
            echo ${{ steps.get-domain.outputs.prop }} > ./dist/CNAME
          fi

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
